apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "ingest-src-postgresql-beer-avro-ef5806e4"
  labels:
    # kafka connect [cluster] name
    strimzi.io/cluster: edh-connect-server
spec:
  class: io.confluent.connect.jdbc.JdbcSourceConnector
  tasksMax: 1
  config:
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    connection.url: "jdbc:postgresql://postgres-postgresql.database.svc.cluster.local:5432/owshq"
    connection.user: "postgres"
    connection.password: "6e8e5979-25c5-44e2-ad76-7a4e8ee68c6f"
    connection.attempts: "2"
    query: "SELECT * FROM public.beer"
    mode: "incrementing"
    topic.prefix: "src-postgres-beer-avro"
    incrementing.column.name: "incr"
    validate.non.null: "false"
    transforms: "createKey,extractInt,InsertTopic,InsertSourceDetails"
    transforms.createKey.type: "org.apache.kafka.connect.transforms.ValueToKey"
    transforms.createKey.fields: "incr"
    transforms.extractInt.type: "org.apache.kafka.connect.transforms.ExtractField$Key"
    transforms.extractInt.field: "incr"
    transforms.InsertTopic.type: "org.apache.kafka.connect.transforms.InsertField$Value"
    transforms.InsertTopic.topic.field: "messagetopic"
    transforms.InsertSourceDetails.type: "org.apache.kafka.connect.transforms.InsertField$Value"
    transforms.InsertSourceDetails.static.field: "messagesource"
    transforms.InsertSourceDetails.static.value: "postgres"
