apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pr-movies-analysis-batch
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "owshq/etl-pr-movies-analysis:3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/pr-movies-analysis-batch.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    # cores: 1
    coreRequest: 250m
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: default
  executor:
    # cores: 1
    coreRequest: 250m
    instances: 2
    memory: "512m"
    labels:
      version: 3.0.0
