apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "ingest-src-mongodb-restaurant-avro-a04181dd"
  labels:
    # kafka connect [cluster] name
    strimzi.io/cluster: edh
spec:
  class: com.mongodb.kafka.connect.MongoSourceConnector
  tasksMax: 1
  config:
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    connection.uri: "mongodb://root:w2nyCRBZKj@mongodb-headless.database.svc.cluster.local:27017"
    topic.prefix: "src.mongodb"
    database: "owshq"
    collection: "restaurant"
    copy.existing: true
    publish.full.document.only: true
